kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mntrng-deploy
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: mntrng
      labels:
        name: mntrng
    spec:
      containers:
      - name: mntrng
        image: eu.gcr.io/GCP_PROJECT/APP_NAME:1.0.0
        imagePullPolicy: Always
        env:
        - name: nli_mbse
          value: "http://emt-mbseqa.nlicge.de"
        - name: nli_secret_key
          value: "8e4c3077-c174-49bc-8a5f-c5377884dab7"
        readinessProbe:
          tcpSocket:
            port: 8089
          initialDelaySeconds: 10
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 8089
